# ----------------------------------------------------------------------------------------------------------------------
# VOLUMES
# ----------------------------------------------------------------------------------------------------------------------
# Docker Volumes defined for each service
volumes:
  mysql-volume:
    name: mysql_data

# ----------------------------------------------------------------------------------------------------------------------
# NETWORKS
# ----------------------------------------------------------------------------------------------------------------------
# dt2-network - This network for DT2 course exercises.
# ----------------------------------------------------------------------------------------------------------------------
networks:
  dt2-network:
    name: dt2-network

services:
  # --------------------------------------------------------------------------------------------------------------------
  # MYSQL SERVICE
  # --------------------------------------------------------------------------------------------------------------------
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    ports:
      - "3308:3306"
    networks:
      - dt2-network
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: passw0rd
    volumes:
      - type: volume
        source: mysql-volume
        target: /var/lib/mysql
    cap_add:
      - SYS_NICE

